// Generated by CoffeeScript 1.6.3
(function() {
  var delay, favoriteTweet, log, settings, startTracking, tweeper, twitter;

  twitter = require('twit');

  settings = require('./settings');

  tweeper = new twitter(settings.twitter);

  log = function(str) {
    return console.log("[favbot] " + str);
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  favoriteTweet = function(tweet) {
    return tweeper.post('favorites/create', {
      id: "" + tweet.id
    }, function(errors, tweet) {
      if (errors) {
        return;
      }
      return log('Tweet by @' + tweet.user.screen_name + ' favorited!');
    });
  };

  startTracking = function() {
    var stream;
    stream = tweeper.stream('statuses/filter', {
      track: settings.keywords.join(', ')
    });
    return stream.on('tweet', function(tweet) {
      log('  Found a tweet from @' + tweet.user.screen_name + " (waiting for " + settings.delay + "s)");
      log('  ' + tweet.text);
      return delay(settings.delay * 1000, function() {
        return favoriteFunc(tweet);
      });
    });
  };

  startTracking();

}).call(this);
